# Activate venv and run Uvicorn in one go
run:
	source .venv/bin/activate && \
	python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000 \
	--ssl-keyfile ./local_cert/local.app.com-key.pem \
	--ssl-certfile ./local_cert/local.app.com.pem